[project]
authors = ["OEM Configuration (temporary user)"]
entry = "src20_fixed_supply.sw"
license = "Apache-2.0"
name = "getFuel_fun"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.4.3" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.21.0" }
